language: python
python:
  - "3.5"
services:
  - postgresql
env:
  - POSTGRESQL_INSTANCE_NAME=postgres
  - POSTGRESQL_USERNAME=postgres
  - POSTGRESQL_PASSWORD=
  - POSTGRESQL_PORT_3306_TCP_ADDR=localhost
  - POSTGRESQL_PORT_3306_TCP_PORT=5432

install: "pip install -r requirements.txt"
before_script:
  - psql -c 'create database postgres;' -U postgres
script: python3 manage.py test